data:
  - changed-files:
      - any-glob-to-any-file: "src/data/**"

ui:
  - changed-files:
      - any-glob-to-any-file: "src/components/**"

hooks:
  - changed-files:
      - any-glob-to-any-file: "src/hooks/**"

services:
  - changed-files:
      - any-glob-to-any-file: "src/services/**"

assets:
  - changed-files:
      - any-glob-to-any-file:
          - "src/assets/**"
          - "public/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "vite.config.*"
          - "package.json"
          - "package-lock.json"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
