content:
  - changed-files:
      - any-glob-to-any-file: "docs/**/*.md"

theme:
  - changed-files:
      - any-glob-to-any-file: "docs/.vitepress/theme/**"

components:
  - changed-files:
      - any-glob-to-any-file: "docs/.vitepress/theme/components/**"

composables:
  - changed-files:
      - any-glob-to-any-file: "docs/.vitepress/theme/composables/**"

assets:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/public/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/.vitepress/config.ts"
          - "package.json"
          - "package-lock.json"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
